### ISSUE TITLE
Migrate Death minigames into main plugin

### ISSUE THREAD

**Issue by JonasFranke** [PrinzPizza42/DeathMinigames#64]
What is the current state? Is it able to be merged into the main plugin?

**Comment by PrinzPizza42** [comment]
In my opinion, yes, the only thing missing right now is everything about the website and some testing with several people.

**Comment by JonasFranke** [comment]
If you want you can create a PR with your files

**Comment by PrinzPizza42** [comment]
I will do that later today

**Comment by PrinzPizza42** [comment]
What is the best way to add my file to the project? If i just copy all of them into the right folder the references for importing and so on wont be working properly

**Comment by PrinzPizza42** [comment]
I also just remembered, that I need to change the naming of my folders from org.example.DeathMinigames to de.luca.DeathMinigames, I will finish and make a PR to my repository, and then we can continue merging the plugins.

**Comment by PrinzPizza42** [comment]
Made the PR, just waiting for you to look over it.

**Comment by JonasFranke** [comment]
> What is the best way to add my file to the project? If i just copy all of them into the right folder the references for importing and so on wont be working properly

prop. just copying and fixing the imports although most of them should still work if you fix the package path

**Comment by JonasFranke** [comment]
You can also add yourself to the codeowners file with the files you add
